import { z } from "zod";

import { rvConditionSchema, rvTypeSchema } from "./enums";

export const inventoryFormSchema = z.object({
  stockNumber: z.string().trim().min(1, "Stock number is required.").max(64),
  vin: z.string().trim().max(32).optional(),
  year: z.coerce.number().int().min(1980).max(2100),
  make: z.string().trim().min(1, "Make is required.").max(100),
  model: z.string().trim().min(1, "Model is required.").max(100),
  floorplan: z.string().trim().max(100).optional(),
  rvType: rvTypeSchema,
  condition: rvConditionSchema,
  msrp: z.coerce.number().nonnegative().optional(),
  salePrice: z.coerce.number().positive("Sale price is required."),
  advertisedPrice: z.coerce.number().nonnegative().optional(),
  lengthFeet: z.coerce.number().positive().optional(),
  widthInches: z.coerce.number().positive().optional(),
  heightInches: z.coerce.number().positive().optional(),
  dryWeightLbs: z.coerce.number().nonnegative().optional(),
  gvwrLbs: z.coerce.number().nonnegative().optional(),
  hitchWeightLbs: z.coerce.number().nonnegative().optional(),
  sleeps: z.coerce.number().int().nonnegative().optional(),
  slideCount: z.coerce.number().int().nonnegative().optional(),
  bedConfiguration: z.string().trim().max(100).optional(),
  bunkhouse: z.boolean().default(false),
  toyHauler: z.boolean().default(false),
  outdoorKitchen: z.boolean().default(false),
  exteriorColor: z.string().trim().max(100).optional(),
  interior: z.string().trim().max(100).optional(),
  description: z.string().trim().max(4000).optional(),
  city: z.string().trim().max(100).optional(),
  state: z.string().trim().max(2).optional(),
  zipCode: z.string().trim().max(10).optional(),
  features: z.string().trim().max(2000).optional(), // comma-separated in the form
});

export type InventoryFormInput = z.infer<typeof inventoryFormSchema>;

export const csvRowSchema = z.object({
  stock_number: z.string().trim().min(1),
  vin: z.string().trim().optional(),
  year: z.coerce.number().int().min(1980).max(2100),
  make: z.string().trim().min(1),
  model: z.string().trim().min(1),
  floorplan: z.string().trim().optional(),
  rv_type: rvTypeSchema,
  condition: rvConditionSchema,
  msrp: z.coerce.number().nonnegative().optional(),
  sale_price: z.coerce.number().positive(),
  advertised_price: z.coerce.number().nonnegative().optional(),
  length_feet: z.coerce.number().positive().optional(),
  dry_weight_lbs: z.coerce.number().nonnegative().optional(),
  gvwr_lbs: z.coerce.number().nonnegative().optional(),
  sleeps: z.coerce.number().int().nonnegative().optional(),
  slide_count: z.coerce.number().int().nonnegative().optional(),
  bunkhouse: z.coerce.boolean().optional(),
  toy_hauler: z.coerce.boolean().optional(),
  outdoor_kitchen: z.coerce.boolean().optional(),
  exterior_color: z.string().trim().optional(),
  description: z.string().trim().optional(),
  city: z.string().trim().optional(),
  state: z.string().trim().optional(),
  zip_code: z.string().trim().optional(),
  features: z.string().trim().optional(),
});

export type CsvRowInput = z.infer<typeof csvRowSchema>;

export const CSV_TEMPLATE_HEADERS = [
  "stock_number",
  "vin",
  "year",
  "make",
  "model",
  "floorplan",
  "rv_type",
  "condition",
  "msrp",
  "sale_price",
  "advertised_price",
  "length_feet",
  "dry_weight_lbs",
  "gvwr_lbs",
  "sleeps",
  "slide_count",
  "bunkhouse",
  "toy_hauler",
  "outdoor_kitchen",
  "exterior_color",
  "description",
  "city",
  "state",
  "zip_code",
  "features",
] as const;
