/**
 * Synthetic demo inventory catalog. All values are fabricated for seed
 * data — see README.md "Demo Data" for the disclosure that ships with this
 * dataset. Prices are in whole dollars here and converted to cents when
 * inserted.
 */
export interface CatalogEntry {
  stockNumber: string;
  vin?: string;
  year: number;
  make: string;
  model: string;
  floorplan: string;
  rvType:
    | "travel_trailer"
    | "fifth_wheel"
    | "class_a"
    | "class_b"
    | "class_c"
    | "toy_hauler"
    | "pop_up"
    | "truck_camper";
  condition: "new" | "used";
  msrp: number;
  salePrice: number;
  advertisedPrice?: number;
  lengthFeet: number;
  dryWeightLbs: number;
  gvwrLbs: number;
  sleeps: number;
  slideCount: number;
  bunkhouse: boolean;
  toyHauler: boolean;
  outdoorKitchen: boolean;
  exteriorColor: string;
  features: string[];
  description: string;
  photoColors: string[]; // one placeholder "photo" generated per color
}

export const CATALOG: CatalogEntry[] = [
  {
    stockNumber: "RV-1001",
    year: 2024,
    make: "Forest River",
    model: "Rockwood",
    floorplan: "2715S",
    rvType: "travel_trailer",
    condition: "new",
    msrp: 44900,
    salePrice: 38900,
    lengthFeet: 31,
    dryWeightLbs: 6100,
    gvwrLbs: 7800,
    sleeps: 6,
    slideCount: 1,
    bunkhouse: true,
    toyHauler: false,
    outdoorKitchen: true,
    exteriorColor: "Alpine White",
    features: ["Outdoor Kitchen", "Bunkhouse", "Solar Prep", "Power Awning"],
    description: "A bunkhouse travel trailer built for family trips, with a full outdoor kitchen.",
    photoColors: ["2b4c7e", "3a6ea5", "1c3a5e"],
  },
  {
    stockNumber: "RV-1002",
    year: 2023,
    make: "Keystone",
    model: "Montana",
    floorplan: "3761FL",
    rvType: "fifth_wheel",
    condition: "used",
    msrp: 92000,
    salePrice: 68500,
    lengthFeet: 41,
    dryWeightLbs: 13400,
    gvwrLbs: 16200,
    sleeps: 4,
    slideCount: 4,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: true,
    exteriorColor: "Champagne",
    features: ["Front Living", "Residential Fridge", "Fireplace", "King Bed"],
    description: "Front-living luxury fifth wheel with four slides and a residential kitchen.",
    photoColors: ["6b4226", "8a5a34", "4a2c17"],
  },
  {
    stockNumber: "RV-1003",
    year: 2024,
    make: "Winnebago",
    model: "View",
    floorplan: "24D",
    rvType: "class_b",
    condition: "new",
    msrp: 168000,
    salePrice: 152500,
    lengthFeet: 25,
    dryWeightLbs: 11500,
    gvwrLbs: 13400,
    sleeps: 2,
    slideCount: 0,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "Granite",
    features: ["Mercedes Sprinter Chassis", "Solar Package", "Diesel Heat"],
    description: "A nimble Class B on the Mercedes Sprinter chassis, easy to drive and park anywhere.",
    photoColors: ["55565a", "35363a", "1f2023"],
  },
  {
    stockNumber: "RV-1004",
    year: 2022,
    make: "Jayco",
    model: "Jay Flight",
    floorplan: "28BHS",
    rvType: "travel_trailer",
    condition: "used",
    msrp: 39000,
    salePrice: 27900,
    lengthFeet: 32,
    dryWeightLbs: 5900,
    gvwrLbs: 7300,
    sleeps: 8,
    slideCount: 1,
    bunkhouse: true,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "Sage",
    features: ["Bunkhouse", "Bunk TV Prep", "Outside Shower"],
    description: "A budget-friendly bunkhouse trailer that sleeps eight comfortably.",
    photoColors: ["3f6b4f", "2c4a37", "578a63"],
  },
  {
    stockNumber: "RV-1005",
    year: 2024,
    make: "Grand Design",
    model: "Momentum",
    floorplan: "395MS",
    rvType: "toy_hauler",
    condition: "new",
    msrp: 128000,
    salePrice: 112900,
    lengthFeet: 44,
    dryWeightLbs: 16800,
    gvwrLbs: 20000,
    sleeps: 6,
    slideCount: 3,
    bunkhouse: false,
    toyHauler: true,
    outdoorKitchen: true,
    exteriorColor: "Onyx",
    features: ["Garage Ramp Door", "Outdoor Kitchen", "Fuel Station", "Patio"],
    description: "A heavy-duty toy hauler with a 14-foot garage and full outdoor entertaining patio.",
    photoColors: ["262626", "3d3d3d", "141414"],
  },
  {
    stockNumber: "RV-1006",
    year: 2023,
    make: "Thor",
    model: "Four Winds",
    floorplan: "31E",
    rvType: "class_c",
    condition: "used",
    msrp: 138000,
    salePrice: 109900,
    lengthFeet: 32,
    dryWeightLbs: 12200,
    gvwrLbs: 14500,
    sleeps: 8,
    slideCount: 1,
    bunkhouse: true,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "Slate Blue",
    features: ["Bunk Beds", "Overcab Bunk", "Backup Camera"],
    description: "A family-friendly Class C with bunk beds over the cab and a rear bunkhouse.",
    photoColors: ["3c5a80", "27405e", "5b7ea6"],
  },
  {
    stockNumber: "RV-1007",
    year: 2024,
    make: "Forest River",
    model: "Cherokee",
    floorplan: "274RK",
    rvType: "travel_trailer",
    condition: "new",
    msrp: 41200,
    salePrice: 34900,
    lengthFeet: 30,
    dryWeightLbs: 5700,
    gvwrLbs: 7100,
    sleeps: 4,
    slideCount: 1,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: true,
    exteriorColor: "Slate",
    features: ["Rear Kitchen", "Outdoor Kitchen", "Power Tongue Jack"],
    description: "A rear-kitchen layout with an outdoor kitchen, ideal for couples who love to cook.",
    photoColors: ["5c5c5c", "3d3d3d", "757575"],
  },
  {
    stockNumber: "RV-1008",
    year: 2021,
    make: "Coachmen",
    model: "Freedom Express",
    floorplan: "192RBS",
    rvType: "travel_trailer",
    condition: "used",
    msrp: 29500,
    salePrice: 19900,
    lengthFeet: 23,
    dryWeightLbs: 4200,
    gvwrLbs: 5400,
    sleeps: 4,
    slideCount: 0,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "White",
    features: ["Lightweight", "Murphy Bed", "Half-ton Towable"],
    description: "A lightweight, half-ton towable trailer — an easy first RV.",
    photoColors: ["8f8f8f", "6b6b6b", "aeaeae"],
  },
  {
    stockNumber: "RV-1009",
    year: 2024,
    make: "Newmar",
    model: "Dutch Star",
    floorplan: "4369",
    rvType: "class_a",
    condition: "new",
    msrp: 512000,
    salePrice: 468000,
    lengthFeet: 43,
    dryWeightLbs: 32500,
    gvwrLbs: 39000,
    sleeps: 4,
    slideCount: 4,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "Pearl",
    features: ["Diesel Pusher", "Residential Kitchen", "Washer/Dryer", "King Bed"],
    description: "A flagship diesel pusher with full residential amenities for full-time living.",
    photoColors: ["7a6a4f", "9c8a63", "5a4d3a"],
  },
  {
    stockNumber: "RV-1010",
    year: 2023,
    make: "Keystone",
    model: "Passport",
    floorplan: "2400BH",
    rvType: "travel_trailer",
    condition: "used",
    msrp: 34500,
    salePrice: 24900,
    lengthFeet: 28,
    dryWeightLbs: 4900,
    gvwrLbs: 6500,
    sleeps: 6,
    slideCount: 0,
    bunkhouse: true,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "Blue",
    features: ["Bunkhouse", "Lightweight", "Outside Speakers"],
    description: "An easy-to-tow bunkhouse trailer for young families getting started.",
    photoColors: ["2d5f8a", "1c3f5c", "4380b3"],
  },
  {
    stockNumber: "RV-1011",
    year: 2024,
    make: "Grand Design",
    model: "Reflection",
    floorplan: "31MB",
    rvType: "fifth_wheel",
    condition: "new",
    msrp: 79500,
    salePrice: 64900,
    lengthFeet: 36,
    dryWeightLbs: 10900,
    gvwrLbs: 13000,
    sleeps: 4,
    slideCount: 3,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: true,
    exteriorColor: "Champagne",
    features: ["Mid Bunk", "Outdoor Kitchen", "Fireplace"],
    description: "A mid-profile fifth wheel with three slides and a cozy fireplace.",
    photoColors: ["8a6d4a", "6b5237", "a4835c"],
  },
  {
    stockNumber: "RV-1012",
    year: 2022,
    make: "Jayco",
    model: "Seismic",
    floorplan: "4113",
    rvType: "toy_hauler",
    condition: "used",
    msrp: 115000,
    salePrice: 89900,
    lengthFeet: 45,
    dryWeightLbs: 17200,
    gvwrLbs: 20500,
    sleeps: 8,
    slideCount: 3,
    bunkhouse: true,
    toyHauler: true,
    outdoorKitchen: true,
    exteriorColor: "Black/Orange",
    features: ["Garage", "Bunkhouse", "Outdoor Kitchen", "Fuel Station"],
    description: "A do-it-all toy hauler with a bunkhouse and full garage for the whole crew.",
    photoColors: ["1a1a1a", "cc5500", "333333"],
  },
  {
    stockNumber: "RV-1013",
    year: 2024,
    make: "Airstream",
    model: "Bambi",
    floorplan: "22FB",
    rvType: "travel_trailer",
    condition: "new",
    msrp: 68900,
    salePrice: 61900,
    lengthFeet: 22,
    dryWeightLbs: 4200,
    gvwrLbs: 5300,
    sleeps: 2,
    slideCount: 0,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "Polished Aluminum",
    features: ["Riveted Aluminum Shell", "Front Bed", "Compact"],
    description: "The iconic riveted-aluminum silhouette in a compact, easy-to-tow size.",
    photoColors: ["c0c0c0", "9a9a9a", "e0e0e0"],
  },
  {
    stockNumber: "RV-1014",
    year: 2023,
    make: "Thor",
    model: "Sanctuary",
    floorplan: "23A",
    rvType: "class_b",
    condition: "used",
    msrp: 172000,
    salePrice: 144900,
    lengthFeet: 24,
    dryWeightLbs: 9800,
    gvwrLbs: 11000,
    sleeps: 2,
    slideCount: 0,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "Silver",
    features: ["4x4 Chassis", "Off-Grid Solar", "Diesel Heat"],
    description: "A 4x4 camper van built for off-grid adventure and boondocking.",
    photoColors: ["4a4a4a", "6e6e6e", "2e2e2e"],
  },
  {
    stockNumber: "RV-1015",
    year: 2024,
    make: "Forest River",
    model: "Wildwood",
    floorplan: "27RE",
    rvType: "travel_trailer",
    condition: "new",
    msrp: 37500,
    salePrice: 31900,
    lengthFeet: 30,
    dryWeightLbs: 5600,
    gvwrLbs: 7000,
    sleeps: 5,
    slideCount: 1,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: true,
    exteriorColor: "White/Blue",
    features: ["Outdoor Kitchen", "Power Awning", "Rear Bath"],
    description: "A value-priced travel trailer with an outdoor kitchen and rear bath layout.",
    photoColors: ["2f6f8f", "1e4a5f", "4a94b8"],
  },
  {
    stockNumber: "RV-1016",
    year: 2022,
    make: "Winnebago",
    model: "Minnie Winnie",
    floorplan: "31G",
    rvType: "class_c",
    condition: "used",
    msrp: 132000,
    salePrice: 98900,
    lengthFeet: 33,
    dryWeightLbs: 12800,
    gvwrLbs: 14500,
    sleeps: 8,
    slideCount: 2,
    bunkhouse: true,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "Cayman Blue",
    features: ["Bunkhouse", "Overcab Bunk", "Two Slides"],
    description: "A spacious Class C with two slides and a rear bunkhouse for the whole family.",
    photoColors: ["1f5f8a", "154060", "3a83ad"],
  },
  {
    stockNumber: "RV-1017",
    year: 2024,
    make: "Keystone",
    model: "Cougar",
    floorplan: "22MLS",
    rvType: "fifth_wheel",
    condition: "new",
    msrp: 52900,
    salePrice: 44900,
    lengthFeet: 27,
    dryWeightLbs: 6900,
    gvwrLbs: 8600,
    sleeps: 4,
    slideCount: 1,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "Slate Gray",
    features: ["Half-Ton Towable", "Fireplace", "King Bed"],
    description: "A half-ton towable fifth wheel that doesn't compromise on comfort.",
    photoColors: ["6a6a6a", "4a4a4a", "8c8c8c"],
  },
  {
    stockNumber: "RV-1018",
    year: 2023,
    make: "Grand Design",
    model: "Imagine",
    floorplan: "2500RL",
    rvType: "travel_trailer",
    condition: "used",
    msrp: 46900,
    salePrice: 37900,
    lengthFeet: 29,
    dryWeightLbs: 5900,
    gvwrLbs: 7500,
    sleeps: 4,
    slideCount: 2,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: true,
    exteriorColor: "Aspen",
    features: ["Outdoor Kitchen", "Two Slides", "Rear Living"],
    description: "A rear-living travel trailer with two slides and a full outdoor kitchen.",
    photoColors: ["7a8f6e", "5c7052", "9bb18d"],
  },
  {
    stockNumber: "RV-1019",
    year: 2024,
    make: "Jayco",
    model: "White Hawk",
    floorplan: "27RB",
    rvType: "travel_trailer",
    condition: "new",
    msrp: 43900,
    salePrice: 36500,
    lengthFeet: 32,
    dryWeightLbs: 6400,
    gvwrLbs: 8000,
    sleeps: 6,
    slideCount: 1,
    bunkhouse: true,
    toyHauler: false,
    outdoorKitchen: true,
    exteriorColor: "White",
    features: ["Bunkhouse", "Outdoor Kitchen", "Solar Prep"],
    description: "A well-equipped bunkhouse trailer with a full outdoor kitchen and solar prep.",
    photoColors: ["5a5a5a", "3f3f3f", "7a7a7a"],
  },
  {
    stockNumber: "RV-1020",
    year: 2021,
    make: "Forest River",
    model: "Sunseeker",
    floorplan: "2440DS",
    rvType: "class_c",
    condition: "used",
    msrp: 118000,
    salePrice: 89500,
    lengthFeet: 25,
    dryWeightLbs: 10900,
    gvwrLbs: 12500,
    sleeps: 5,
    slideCount: 1,
    bunkhouse: false,
    toyHauler: false,
    outdoorKitchen: false,
    exteriorColor: "Red/Silver",
    features: ["Dinette Slide", "Overcab Bunk", "Backup Camera"],
    description: "A compact, driveable Class C with a dinette slide and overcab sleeping.",
    photoColors: ["8a2a2a", "6a1f1f", "aa3a3a"],
  },
];
